{{- if .Values.budget.minAvailable -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "laradock-kubernetes.fullname" . }}
  labels:
{{ include "laradock-kubernetes.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "laradock-kubernetes.name" . }}
  minAvailable: {{ .Values.budget.minAvailable }}
  {{- end -}}
