apiVersion: v1
kind: Secret
metadata:
  name: {{ template "laradock-kubernetes.fullname" . }}-secrets
  labels:
{{ include "laradock-kubernetes.labels" . | indent 4 }}
type: Opaque
data:
  APP_KEY: {{ .Values.APP_KEY | b64enc | quote }}
  DB_HOST: {{ .Values.DB_HOST | b64enc | quote }}
  DB_DATABASE: {{ .Values.DB_DATABASE | b64enc | quote }}
  DB_USERNAME: {{ .Values.DB_USERNAME | b64enc | quote }}
  DB_PASSWORD: {{ .Values.DB_PASSWORD | b64enc | quote }}
  REDIS_HOST: {{ .Values.REDIS_HOST | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.REDIS_PASSWORD | b64enc | quote }}
  PUSHER_APP_ID: {{ .Values.PUSHER_APP_ID | b64enc | quote }}
  PUSHER_APP_KEY: {{ .Values.PUSHER_APP_KEY | b64enc | quote }}
  PUSHER_APP_SECRET: {{ .Values.PUSHER_APP_SECRET | b64enc | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.AWS_ACCESS_KEY_ID | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.AWS_SECRET_ACCESS_KEY | b64enc | quote }}
  AWS_DEFAULT_REGION: {{ .Values.AWS_DEFAULT_REGION | b64enc | quote }}
  AWS_BUCKET: {{ .Values.AWS_BUCKET | b64enc | quote }}
  MAIL_USERNAME: {{ .Values.MAIL_USERNAME | b64enc | quote }}
  MAIL_PASSWORD: {{ .Values.MAIL_PASSWORD | b64enc | quote }}
  MIX_PUSHER_APP_KEY: {{ .Values.MIX_PUSHER_APP_KEY | b64enc | quote }}
  MIX_PUSHER_APP_CLUSTER: {{ .Values.MIX_PUSHER_APP_CLUSTER | b64enc | quote }}



---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "laradock-kubernetes.fullname" . }}-config
  labels:
{{ include "laradock-kubernetes.labels" . | indent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.config }}
    {{ $key }}: {{ $val | b64enc | quote }}
  {{- end}}
