apiVersion: v1
kind: Service
metadata:
  name: {{ include "laradock-kubernetes.fullname" . }}
  labels:
{{ include "laradock-kubernetes.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "laradock-kubernetes.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
